--beim ersten Ausführen die drop tables auskommentieren

DROP TABLE TicketAnruf CASCADE CONSTRAINTS PURGE;
DROP TABLE Ticket CASCADE CONSTRAINTS PURGE;
DROP TABLE Anruf CASCADE CONSTRAINTS PURGE;
DROP TABLE Mitarbeiter CASCADE CONSTRAINTS PURGE;
DROP TABLE Kunde CASCADE CONSTRAINTS PURGE;
DROP TABLE Abteilung CASCADE CONSTRAINTS PURGE;
DROP TABLE Problemkategorie CASCADE CONSTRAINTS PURGE;
DROP TABLE Status CASCADE CONSTRAINTS PURGE;

CREATE TABLE Problemkategorie (
                                  ProblemkategorieId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  Bezeichnung VARCHAR(50) NOT NULL,
                                  Beschreibung VARCHAR(255) NOT NULL
);

CREATE TABLE Status (
                        StatusId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        Bezeichnung VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Abteilung(
                          AbteilungsId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          Abteilungsname VARCHAR(100) NOT NULL,
                          Abteilungsleiter INT
); --alter table für Mitarbeiter

CREATE TABLE Kunde(
    KundenId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nachname VARCHAR(50) NOT NULL,
    Vorname VARCHAR(50) NOT NULL,
    Telefonnummer VARCHAR(20),
    Email VARCHAR(100)
);

CREATE TABLE Mitarbeiter(
    MitarbeiterId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VorgesetzterId INT, --eine Person ist immer der oberste Chef
    AbteilungsId INT NOT NULL,
    Nachname VARCHAR(50) NOT NULL,
    Vorname VARCHAR(50) NOT NULL,

    FOREIGN KEY(VorgesetzterId)
                        REFERENCES Mitarbeiter (MitarbeiterId)
                        ON DELETE SET NULL,
    FOREIGN KEY(AbteilungsId)
                        REFERENCES Abteilung (AbteilungsId)
);

CREATE TABLE Anruf(
    AnrufId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DatumUhrzeit TIMESTAMP NOT NULL,
    DauerSekunden DECIMAL(5) NOT NULL,
    KundenId INT, --wenn Kunde nicht mehr Kunde, Anruf noch für Statistik
    MitarbeiterId INT, --genau wie Kunde

    FOREIGN KEY (KundenId)
                  REFERENCES Kunde (KundenId)
                  ON DELETE SET NULL,
    FOREIGN KEY (MitarbeiterId)
            REFERENCES Mitarbeiter (MitarbeiterId)
            ON DELETE SET NULL
);

CREATE TABLE Ticket (
                        TicketId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ProblemkategorieId INT, --nicht jeder Anruf ist/hat ein Problem
                        MitarbeiterId INT, --selbe wie bei Anruf Table
                        KundenId INT, --selbe wie bei Anruf Table
                        Beschreibung VARCHAR(255) NOT NULL,
                        Problemlösungsschritte VARCHAR(255),
                        StatusId INT NOT NULL,

                        FOREIGN KEY (ProblemkategorieId)
                            REFERENCES Problemkategorie (ProblemkategorieId)
                                ON DELETE SET NULL,
                        FOREIGN KEY (MitarbeiterId)
                            REFERENCES Mitarbeiter (MitarbeiterId)
                                ON DELETE SET NULL,
                        FOREIGN KEY (KundenId)
                            REFERENCES Kunde (KundenId)
                                ON DELETE SET NULL,
                        FOREIGN KEY (StatusId)
                            REFERENCES Status (StatusId)
                                ON DELETE SET NULL
);

CREATE TABLE TicketAnruf(
    TicketAnrufId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketId INT,
    AnrufId INT,

    FOREIGN KEY (TicketId)
                    REFERENCES Ticket (TicketId)
                    ON DELETE SET NULL,
    FOREIGN KEY (AnrufId)
                    REFERENCES Anruf (AnrufId)
                    ON DELETE SET NULL
);

------------ ALTERATIONS ----------

ALTER TABLE Abteilung
    ADD(
        FOREIGN KEY (Abteilungsleiter)
            REFERENCES Mitarbeiter (MitarbeiterId)
        );

------------ INTEGRITÄTSBEDINGUNGEN ----------

--NOT NULL, UNIQUE, PRIMARY KEY, FOREIGN KEY bei CREATE TABLE

ALTER TABLE Kunde
ADD (
    CONSTRAINT VornameGroesser0 CHECK ( LENGTH(Vorname) > 0 ),
    CONSTRAINT NachnameGroesser0 CHECK ( LENGTH(Nachname) > 0 )
    );

ALTER TABLE Kunde
    ADD (
        CONSTRAINT EmailWithAt CHECK ( REGEXP_LIKE(Email, '^.*@.*$') )
        );

ALTER TABLE Anruf
ADD (
    CONSTRAINT AnrufDauerGroesser0 CHECK ( DauerSekunden > 0 )
    );

ALTER TABLE Kunde
ADD (
    CONSTRAINT MindestensEineKontaktmoeglichkeitMussGegebenSein CHECK ( Telefonnummer IS NOT NULL OR Email IS NOT NULL )
    );


------------ BEISPIELDATEN ------------

INSERT INTO Status (Bezeichnung) VALUES ( 'Erstellt');
INSERT INTO Status (Bezeichnung) VALUES ('in Bearbeitung');
INSERT INTO Status (Bezeichnung) VALUES ('Erledigt');
INSERT INTO Status (Bezeichnung) VALUES ('Geschlossen');

INSERT INTO Problemkategorie (Bezeichnung, Beschreibung) VALUES ('Mängel', 'Falls Mängel festgestellt werden');
INSERT INTO Problemkategorie (Bezeichnung, Beschreibung) VALUES ('Bedienung', 'Fragen zur Bedienung');
INSERT INTO Problemkategorie (Bezeichnung, Beschreibung) VALUES ('Retouren', 'Infos für Retouren');

INSERT INTO Abteilung (Abteilungsname, Abteilungsleiter) VALUES ('Vertrieb', NULL); --2
INSERT INTO Abteilung (Abteilungsname, Abteilungsleiter) VALUES ('Marketing', NULL); --1
INSERT INTO Abteilung (Abteilungsname, Abteilungsleiter) VALUES ('Produktion', NULL); --3

INSERT INTO Kunde (Nachname, Vorname, Telefonnummer, Email) VALUES ('Peter', 'Hans', '0221999985', 'hans.peter@web.de');
INSERt INTO Kunde (Nachname, Vorname, Telefonnummer, Email) VALUES ('Frosch', 'Walter', '0221999985-60', 'walter.frosch@zigarette.de');
INSERT INTO Kunde (Nachname, Vorname, Telefonnummer, Email) VALUES ('Holland', 'Tom', '01578 1234567', 'tom.holland@spider.man');

INSERT INTO Mitarbeiter (VorgesetzterId, AbteilungsId, Nachname, Vorname) VALUES (NULL, 1, 'Doe', 'Jane');
INSERT INTO Mitarbeiter (VorgesetzterId, AbteilungsId, Nachname, Vorname) VALUES (NULL, 2, 'Doe', 'John');
INSERT INTO Mitarbeiter (VorgesetzterId, AbteilungsId, Nachname, Vorname) VALUES (1, 3, 'Mustermann', 'Max');
INSERT INTO MITARBEITER (VorgesetzterId, AbteilungsId, Nachname, Vorname) VALUES (NULL, 1, 'Vorgesetzer1', 'noName');
INSERT INTO MITARBEITER (VorgesetzterId, AbteilungsId, Nachname, Vorname) VALUES (NULL, 1, 'Vorgesetzte1', 'noName');

UPDATE ABTEILUNG SET ABTEILUNGSLEITER = 2 WHERE ABTEILUNGSID = 1;
UPDATE ABTEILUNG SET ABTEILUNGSLEITER = 1 WHERE ABTEILUNGSID = 2;
UPDATE ABTEILUNG SET ABTEILUNGSLEITER = 3 WHERE ABTEILUNGSID = 3;

UPDATE Mitarbeiter SET VORGESETZTERID = 4 WHERE MITARBEITERID = 1;
UPDATE Mitarbeiter SET VORGESETZTERID = 5 WHERE MITARBEITERID = 2;

INSERT INTO Anruf (DatumUhrzeit, DauerSekunden, KundenId, MitarbeiterId) VALUES (TO_TIMESTAMP('2025-08-10 12:15:00', 'YYYY-MM-DD HH24:MI:SS'), 312, 1, 2);
INSERT INTO Anruf (DatumUhrzeit, DauerSekunden, KundenId, MitarbeiterId) VALUES (TO_TIMESTAMP('2025-06-01 14:31:12', 'YYYY-MM-DD HH24:MI:SS'), 5574, 2, 3);
INSERT INTO Anruf (DatumUhrzeit, DauerSekunden, KundenId, MitarbeiterId) VALUES (TO_TIMESTAMP('2025-10-12 16:42:52', 'YYYY-MM-DD HH24:MI:SS'), 2259, 3, 1);

INSERT INTO Ticket (ProblemkategorieId, MitarbeiterId, KundenId, Beschreibung, Problemlösungsschritte, StatusId) VALUES (1, 3, 1, 'Waschmaschine kaputt', '1. Auftrag eingetragen\n2. Auftrag weitergeleitet', 2);
INSERT INTO Ticket (ProblemkategorieId, MitarbeiterId, KundenId, Beschreibung, Problemlösungsschritte, StatusId) VALUES (1, 2, 2, 'Zigarettenautomat kaputt', '1. Auftrag eingetragen\n2. Auftrag weitergeleitet', 2);
INSERT INTO Ticket (ProblemkategorieId, MitarbeiterId, KundenId, Beschreibung, Problemlösungsschritte, StatusId) VALUES (2, 3, 2, 'Zigarettenausgabe einstellen', '1. Auftrag eingetragen\n2. Auftrag weitergeleitet', 2);
INSERT INTO Ticket (ProblemkategorieId, MitarbeiterId, KundenId, Beschreibung, Problemlösungsschritte, StatusId) VALUES (2, 1, 3, 'Wie funktioniert der Spiderman-Anzug', '1. Auf FAQ-Seite verwiesen', 4);
INSERT INTO Ticket (ProblemkategorieId, MitarbeiterId, KundenId, Beschreibung, Problemlösungsschritte, StatusId) VALUES (3, 1, 3, 'Rücksendung vom Anzug', '1. Auftrag erstellt und Kunde Etikette ausgedruckt', 1);

INSERT INTO TicketAnruf (TicketId, AnrufId) VALUES (1, 1);
INSERT INTO TicketAnruf (TicketId, AnrufId) VALUES (2, 2);
INSERT INTO TicketAnruf (TicketId, AnrufId) VALUES (3, 2);

COMMIT;
